# Step 1: Import the pandas library

In [2]:
import pandas as pd

Step 2: Create a DataFrame using the student data

In [3]:
data = {
    "StudentID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    "Name": ["Ram", "Sheela", "Sam", "Maya", "John", "Sara", "Karan", "Annie", "Maran", "Pavi"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19, 22, 20],
    "Marks": [88, 75, 92, 65, 78, 85, 70, 95, 60, 80],
    "Grade": ["A", "B", "A", "C", "B", "A", "B", "A", "C", "B"]
}

df = pd.DataFrame(data)
df

   StudentID    Name  Age  Marks Grade
0       1001     Ram   20     88     A
1       1002  Sheela   21     75     B
2       1003     Sam   19     92     A
3       1004    Maya   22     65     C
4       1005    John   20     78     B
5       1006    Sara   21     85     A
6       1007   Karan   23     70     B
7       1008   Annie   19     95     A
8       1009   Maran   22     60     C
9       1010    Pavi   20     80     B

Step 4: Save DataFrame as CSV File

In [4]:
df.to_csv("students.csv", index=False)

Step 5: Reload the CSV File

In [5]:
df_new = pd.read_csv("students.csv")
df_new

   StudentID    Name  Age  Marks Grade
0       1001     Ram   20     88     A
1       1002  Sheela   21     75     B
2       1003     Sam   19     92     A
3       1004    Maya   22     65     C
4       1005    John   20     78     B
5       1006    Sara   21     85     A
6       1007   Karan   23     70     B
7       1008   Annie   19     95     A
8       1009   Maran   22     60     C
9       1010    Pavi   20     80     B

Step 6: Display First 3 Rows

In [6]:
df_new.head(3)

   StudentID    Name  Age  Marks Grade
0       1001     Ram   20     88     A
1       1002  Sheela   21     75     B
2       1003     Sam   19     92     A

Step 7: Display Statistical Summary

In [7]:
df_new.describe()

        StudentID        Age      Marks
count    10.00000  10.000000  10.000000
mean   1005.50000  20.700000  78.800000
std       3.02765   1.337494  11.535453
min    1001.00000  19.000000  60.000000
25%    1003.25000  20.000000  71.250000
50%    1005.50000  20.500000  79.000000
75%    1007.75000  21.750000  87.250000
max    1010.00000  23.000000  95.000000

Step 8:  Shape of the DataFrame

In [8]:
df_new.shape

(10, 5)

Step 9: Display Data Types

In [9]:
df_new.dtypes

StudentID     int64
Name         object
Age           int64
Marks         int64
Grade        object
dtype: object

Step 10: Display Complete DataFrame Information

In [10]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes